# Scala CircleCI 2.0 configuration file
#
version: 2.0
jobs:
  test:
    docker:
    - image: innfactory/gcloud-scala-ci:1.1.0
    - image: google/cloud-sdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.sbt" }}
        - v1-dependencies-
    - run:
        name: "run datastore"
        command: |
          gcloud components install cloud-datastore-emulator
          gcloud beta emulators datastore start --no-store-on-disk --consistency=1.0
    - run:
        name: "test with sbt"
        command: |
          sbt test
    - save_cache:
        paths:
        - "~/.iv2/cache"
        - "~/.sbt"
        - "~/.m2"
        key: v1-dependencies-{{ checksum "build.sbt" }}
workflows:
  version: 2
  akka-persistence-gcp-datastore-pipeline:
    jobs:
    - test